### ISSUE TITLE
Doubt regarding the normalization of the depthmap during preprocessing of dataset in the training procedure

### ISSUE THREAD

**Issue by iacopo97** [JiaDingCN/GeminiFusion#11]
Thank you for your awesome work!!! 
I would like to be clarified of a doubt I have. During the normalization procedure are you dividing the values of the depthmap by 255? Is this the only normalization you applied to the depth in the dataset NYUDv2, even if it is a uint16 datum?

**Comment by JiaDingCN** [comment]
Hi, you may refer to the [transform part](https://github.com/JiaDingCN/GeminiFusion/blob/1f102f6451ec7cd4546278ef2022f639f979c60b/main.py#L242). Does that solve your question about normalization procedure?

**Comment by iacopo97** [comment]
Thank you very much!! I don't understand though why you divide the depthmap by 255. Is your depthmap in HHA format? From the dataset Nyudv2 that you provided seems to me that the depthmap is a uint16 matrix, therefore I would have divide the values of the map by 2**16 -1 not 255.

**Comment by iacopo97** [comment]
I have another question about the evaluation on NYUDV2 dataset. Is it performed single scale or multiscale?

**Comment by JiaDingCN** [comment]
We follow the same setting as TokenFusion. Dividing the depthmap by 255 is for image normalization. For the NYUDV2 dataset, we take the multiscale inputs.
