### ISSUE TITLE
Unable to reproduce the evaluation results on NYUv2 and SUNRGBD dataset

### ISSUE THREAD

**Issue by bqm1111** [JiaDingCN/GeminiFusion#12]
Hi,

I am trying to reproduce your reported evaluation scores on NYUv2 and SUNRGBD dataset. I used MiT_B5 model  but the results I got are far less than what you claimed in the paper. In NYUv2, I got only 51.9 meanIOU compared to 57.7 in the paper. In SUNRGBD, I got only 49.5 compared to 53.3 in the paper. Furthermore, the evaluation score printed by your code is confusing to me. Why do you have 3 different IoU scores for (RGB), (depth), (ens) separately? What is (ens) by the way?

**Comment by iacopo97** [comment]
I don't know about the first problem, concerning the training. I understood from the code that the decoder is used to process RGB features and other modalities features too (RGB IoU and Depth IoU). Therefore it is shared across the features and ens comes from a particulare alpha blending of the RGB and DEPTH decoded features

**Comment by JiaDingCN** [comment]
Hi, I have checked and reruned this code many times and the results is fine. According to my experience, this training problem may becase of the dataset you prepared or the enveriment. You may try to evaluate the provided checkpoints first and see whether the results are the same as reported. For the decoder output, we have two branches: image and lidar(or another modal), both or them will output a prediction and the 'ens' means the two outputs are Weighted added. The weight is learnable. We follow the same setting as TokenFusion and you may check the TokenFusion paper or code to find more details.
