### ISSUE TITLE
Batch and config of NYUDv2

### ISSUE THREAD

**Issue by iacopo97** [JiaDingCN/GeminiFusion#13]
Hi thank you for your work can you tell me which is the config you used for training the network on nyudv2 (batch ecc..). i would like to know the exact transformation that you have done to the data during training, since in the dataset you provide the dimension of the depth map and the rgb map is different

**Comment by JiaDingCN** [comment]
Hi, you can find the config from [commands](https://github.com/JiaDingCN/GeminiFusion?tab=readme-ov-file#train) and the [main.py](https://github.com/JiaDingCN/GeminiFusion/blob/1f102f6451ec7cd4546278ef2022f639f979c60b/main.py#L85). You can find the transformation related code [here](https://github.com/JiaDingCN/GeminiFusion/blob/1f102f6451ec7cd4546278ef2022f639f979c60b/main.py#L242)
