### ISSUE TITLE
Which are the weights for backbones of the swin transformer?

### ISSUE THREAD

**Issue by iacopo97** [JiaDingCN/GeminiFusion#14]
I cannot find the right backbone for the swin transformer, Can you help me?

**Comment by h-0-0** [comment]
Second this.

**Comment by JiaDingCN** [comment]
Please download from the [offical project](https://github.com/microsoft/Swin-Transformer?tab=readme-ov-file#main-results-on-imagenet-with-pretrained-models). The version we use is V1.

**Comment by h-0-0** [comment]
Thanks 🙏
