### ISSUE TITLE
无法成功运行

### ISSUE THREAD

**Issue by zzz-0930** [JiaDingCN/GeminiFusion#15]
您好，您能告诉我这个问题该怎么去解决吗？
![image](https://github.com/user-attachments/assets/46f1a81a-3b94-46c2-bfc7-720a452ee1b9)

**Comment by JiaDingCN** [comment]
You need to download the checkpoint file 'mit_b5.pth' first. Please download from [here](https://github.com/NVlabs/SegFormer)
