### ISSUE TITLE
Model Zoo Download Links Not Working

### ISSUE THREAD

**Issue by TowsifAbir** [JiaDingCN/GeminiFusion#2]
Hi, congratulations on the great work.

While trying to download the models from the model zoo, I've noticed that the links aren't working. Some of them just takes you back to the main branch. Can you please see to it?

**Comment by JiaDingCN** [comment]
Thank you for your interest in our work! Yes. Actually, for some corporate reasons, we have selected the best models on each task to make public. We are still working on making more checkpoints publicly available, and in addition to that, you can choose to train on your own using our code, and the accuracy should be aligned.
