### ISSUE TITLE
Detailed questions about the paper and code

### ISSUE THREAD

**Issue by EunNamCho** [JiaDingCN/GeminiFusion#3]
As someone who studies Multimodal Fusion, I found your paper really interesting! I was also thinking about ways to improve cross attention calculation, and I was impressed by your idea of ​​solving the problem in a cool way using a pixel-wise method.

I would like to ask you four questions to better understand your methodology.

1. I don't quite understand the idea of ​​performing attention calculations between pixels.
    - Is it patched and not used for projection?
    - From the explanation, seeing that $i$ is within the range of d, it seems that the operation is performed in the dimension of $X\in\mathbb{R}^{n\times d}$ token.
2. Pixel-wise attention operations are **_difficult to find in the code_**.
   - The noise and relation score from the formula are clearly visible, but pixel-wise calculations are not visible.
3. Through which modules **_intra modality_** and **_inter modality_** were achieved, and **_dynamically_**, what does this mean?
   - Is it correct that the green line is self attention and the red line is cross attention, meaning intra and inter respectively?
   - I still don't know why you mentioned **_dynamically_**.
![스크린샷 2024-06-12 205050](https://github.com/JiaDingCN/GeminiFusion/assets/70051949/8f0a4810-4acf-489d-bcfd-5635b2e7031d)
4. And through pixel-wise attention, only the calculation amount of cross attention is saved to 99.2%, and **_self attention remains the same?_**

I know you're busy, but thank you for reading my question :)

**Comment by EunNamCho** [comment]
I'm sorry for frequently asking questions. Additionally, I have two more questions, so I'm leaving this comment.

### [Q1.]
The first question is about the GeminiFusion technique. The understanding based on Figure 2b and the understanding based on the equations seem to conflict with each other.

Assuming there are $n$ tokens of $d$ dimensions for each modality($tokens \in \mathbb{R}^{n\times d})$ , I will only talk about the operation results of the RGB tokens.

1. In the conventional $Cross Attention$, to obtain the $i$-th RGB token, we need to perform the attention operation between the $i$-th RGB $Query$ and the $Key$ and $Value$ of all the remaining Depth tokens.

2. Based on Figure 2b, I understood that, unlike the conventional $Cross Attention$, to obtain the $i$-th RGB token, of course relation score and noise are added, but overall, we only need to perform the attention operation between the $i$-th RGB $Query$ and the $i$-th Depth token's $Key$ and $Value$ .

3. Based on Equations (2) and (6), to obtain the $i$-th **_dimension_** ($\frac{i}{d}$) of **_all tokens_**, you need to perform the attention operation between the $i$-th dimensions of all RGB tokens and the $i$-th **_dimensions_** of the Depth tokens. This is because it is explained that $i$ is within the range of $d$ (dimension of the token).

Logically, case 2 seems reasonable, but can you explain which one is actually applied? Looking at the code, it seems to correspond to case 1, which makes it more confusing.



### [Q2.]
The second question is about Figure 5. The reason for adding noise is (ii) Softmax function limitation in the per-pixel attention mechanism, but I don't understand what is implied in Figure 5.

Thank you for your previous answer :)

**Comment by JiaDingCN** [comment]
Yes, case 2 is used by GeminiFusion. To  better understand it, you can run the code by yourself and debug. Our method is applied in [these lines](https://github.com/JiaDingCN/GeminiFusion/blob/c3dccea9a3576a7531c6c3b4e7dc8de2b9d4e182/models/mix_transformer.py#L198). Figure 5 shows how the noise affects the attention map. The left one is with noise and the right one is w/o noise.
