### ISSUE TITLE
Cannot run successfully

### ISSUE THREAD

**Issue by peter-wang321** [JiaDingCN/GeminiFusion#6]
Great work! Thanks for releasing the code. However, I cannot run the code successfully based on the instructions. Have you tested it by rebuilding a new conda environment?

Thanks!

**Comment by JiaDingCN** [comment]
Thank you for your attention! The code of the project is based on open source projects and has been tested repeatedly by myself. If you can not run properly, would you please post error messages or refer to the corresponding open source project?

**Comment by peter-wang321** [comment]
Which Python/Pytorch version did you use? When I use Python 3.6 following the instructions:
python==3.6
pytorch==1.7.1
torchvision==0.8.2
numpy==1.19.2
The installation of opencv-python is very time-consuming. Thus I changed it to Python 3.8. 
and then:
pip install mmcv
pip install timm

I am still working on it, but first check whether the issue of python version. Thanks.

**Comment by peter-wang321** [comment]
I follow the instructions of the repo. But I changed the python from 3.6 to Python 3.8. 
Besides, I install mmdet and mmcv with the following commands:
$ pip install mmdet==2.25.0
$ pip install mmcv-full==2.0.0cr4
since just this combination of mmdet and mmcv works well without the error like incompatible.

But I still encountered the issue as follows:

$ CUDA_VISIBLE_DEVICES=0,1,2 python -m torch.distributed.launch --nproc_per_node=3  --use_env main.py --backbone mit_b3 --dataset nyudv2 -c nyudv2_mit_b3
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
main.py --backbone mit_b3 --dataset nyudv2 -c nyudv2_mit_b3
main.py --backbone mit_b3 --dataset nyudv2 -c nyudv2_mit_b3
main.py --backbone mit_b3 --dataset nyudv2 -c nyudv2_mit_b3
-----------------Model Params--------------------------------------
backbone: mit_b3
dpr: 0.4
--------------------------------------------------------------
-----------------Model Params--------------------------------------
backbone: mit_b3
dpr: 0.4
--------------------------------------------------------------
-----------------Model Params--------------------------------------
backbone: mit_b3
dpr: 0.4
--------------------------------------------------------------
Traceback (most recent call last):
  File "main.py", line 678, in <module>
Traceback (most recent call last):
  File "main.py", line 678, in <module>
Traceback (most recent call last):
  File "main.py", line 678, in <module>
    main()
  File "main.py", line 532, in main
    main()
  File "main.py", line 532, in main
    main()
  File "main.py", line 532, in main
    segmenter, param_groups = create_segmenter(
  File "main.py", line 197, in create_segmenter
    segmenter, param_groups = create_segmenter(
  File "main.py", line 197, in create_segmenter
    segmenter, param_groups = create_segmenter(
  File "main.py", line 197, in create_segmenter
    segmenter = WeTr(backbone, num_classes, n_heads, dpr, drop_rate)
  File "/GeminiFusion/models/segformer.py", line 270, in __init__
    segmenter = WeTr(backbone, num_classes, n_heads, dpr, drop_rate)
  File "/GeminiFusion/models/segformer.py", line 270, in __init__
    segmenter = WeTr(backbone, num_classes, n_heads, dpr, drop_rate)
  File "/GeminiFusion/models/segformer.py", line 270, in __init__
    self.encoder = getattr(mix_transformer, backbone)(n_heads, dpr, drop_rate)
  File "/GeminiFusion/models/mix_transformer.py", line 708, in __init__
    self.encoder = getattr(mix_transformer, backbone)(n_heads, dpr, drop_rate)
  File "/GeminiFusion/models/mix_transformer.py", line 708, in __init__
    self.encoder = getattr(mix_transformer, backbone)(n_heads, dpr, drop_rate)
  File "/GeminiFusion/models/mix_transformer.py", line 708, in __init__
    super(mit_b3, self).__init__(
  File "/GeminiFusion/models/mix_transformer.py", line 435, in __init__
    super(mit_b3, self).__init__(
  File "/GeminiFusion/models/mix_transformer.py", line 435, in __init__
    super(mit_b3, self).__init__(
  File "/GeminiFusion/models/mix_transformer.py", line 435, in __init__
    [
  File "/GeminiFusion/models/mix_transformer.py", line 436, in <listcomp>
    [
  File "/GeminiFusion/models/mix_transformer.py", line 436, in <listcomp>
    [
  File "/GeminiFusion/models/mix_transformer.py", line 436, in <listcomp>
    Block(
  File "/GeminiFusion/models/mix_transformer.py", line 266, in __init__
    Block(
  File "/GeminiFusion/models/mix_transformer.py", line 266, in __init__
    Block(
  File "/GeminiFusion/models/mix_transformer.py", line 266, in __init__
    self.attn = Attention(
  File "/GeminiFusion/models/mix_transformer.py", line 123, in __init__
    self.attn = Attention(
  File "/GeminiFusion/models/mix_transformer.py", line 123, in __init__
    self.attn = Attention(
  File "/GeminiFusion/models/mix_transformer.py", line 123, in __init__
    self.cross_attn_0_to_1 = nn.MultiheadAttention(
TypeError: __init__() got an unexpected keyword argument 'batch_first'
    self.cross_attn_0_to_1 = nn.MultiheadAttention(
TypeError: __init__() got an unexpected keyword argument 'batch_first'
    self.cross_attn_0_to_1 = nn.MultiheadAttention(
TypeError: __init__() got an unexpected keyword argument 'batch_first'
Traceback (most recent call last):
  File "/anaconda3/envs/GeminiF/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/anaconda3/envs/GeminiF/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/anaconda3/envs/GeminiF/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/anaconda3/envs/GeminiF/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/anaconda3/envs/GeminiF/bin/python', '-u', 'main.py', '--backbone', 'mit_b3', '--dataset', 'nyudv2', '-c', 'nyudv2_mit_b3']' returned non-zero exit status 1.

**Comment by peter-wang321** [comment]
Thanks a lot. I have solved the above issues by deleting the 'batch_first'. in the attention operator. But it seems that there is no pretrained backbone file like:
"pretrained/swin_large_patch4_window12_384_22kto1k.pth"
"pretrained/swin_large_patch4_window7_224_22k.pth"
"pretrained/mit_b3.pth"
"pretrained/mit_b5.pth"

Provided pretrained models are all about the GeminiFusion, right? Could you give some advice to  look for the backbone used here. The TokerFusion project's link for weights has nothing now. 
Thanks a lot.

**Comment by JiaDingCN** [comment]
1. batch_first is very important, please do not delete it. According to [this issue](https://github.com/Noble-Lab/casanovo/issues/9#issuecomment-1058881438), maybe you need to upgrade your PyTorch version.
2. Download the pretrained segformer from [the link in the tokenfusion readme](https://github.com/JiaDingCN/GeminiFusion/blob/main/README-TokenFusion.md#semantic-segmentation) and the pretrained swin transformer from the [official repo](https://github.com/microsoft/Swin-Transformer#main-results-on-imagenet-with-pretrained-models)

**Comment by peter-wang321** [comment]
Thanks a lot for your timely response. After updating the Pytorch version to Pytorch 1.9.0. The "batch_first" issue is solved. However, I still encountered questions when using the provided command for training either using swin_tiny or mit_b3 on the nyudv2 dataset. 

It mainly contains errors like:

File "/GeminiFusion/utils/transforms.py", line 308, in __call__
    sample[key] = torch.from_numpy(sample[key].transpose((2, 0, 1))).to(
TypeError: can't convert np.ndarray of type numpy.uint16. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

[ERROR] 2024-08-16 07:40:09,290 api: failed (exitcode: 1) local_rank: 0 (pid: 939546) of binary: /anaconda3/envs/GeminiF/bin/python
[ERROR] 2024-08-16 07:40:09,290 local_elastic_agent: [default] Worker group failed


To further make sure the basic functions of the code. I changed 3 GPUs settings to 1 GPU training using the following command:

(GeminiF) [GeminiFusion]$ CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.run --nproc_per_node=1  --use_env main.py --backbone mit_b3 --dataset nyudv2 -c nyu
dv2_mit_b3

However, I found that the issue remains, the complete infos are as follows:

(GeminiF) [GeminiFusion]$ CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.run --nproc_per_node=1  --use_env main.py --backbone mit_b3 --dataset nyudv2 -c nyu
dv2_mit_b3
[INFO] 2024-08-16 07:39:44,248 run: Running torch.distributed.run with args: ['/anaconda3/envs/GeminiF/lib/python3.8/site-packages/torch/distributed/run.py', '--nproc_per_node=1', '--use_env', 'main.py', '--backbone', 'mit_b3', '--dataset', 'nyudv2', '-c', 'nyudv2_mit_b3']
[INFO] 2024-08-16 07:39:44,249 run: Using nproc_per_node=1.
[INFO] 2024-08-16 07:39:44,249 api: Starting elastic_operator with launch configs:
  entrypoint       : main.py
  min_nodes        : 1
  max_nodes        : 1
  nproc_per_node   : 1
  run_id           : none
  rdzv_backend     : static
  rdzv_endpoint    : 127.0.0.1:29500
  rdzv_configs     : {'rank': 0, 'timeout': 900}
  max_restarts     : 3
  monitor_interval : 5
  log_dir          : None
  metrics_cfg      : {}

[INFO] 2024-08-16 07:39:44,250 local_elastic_agent: log directory set to: /tmp/torchelastic_73suzzko/none_td9et18n
[INFO] 2024-08-16 07:39:44,250 api: [default] starting workers for entrypoint: python
[INFO] 2024-08-16 07:39:44,250 api: [default] Rendezvous'ing worker group
[INFO] 2024-08-16 07:39:44,250 static_tcp_rendezvous: Creating TCPStore as the c10d::Store implementation
/anaconda3/envs/GeminiF/lib/python3.8/site-packages/torch/distributed/elastic/utils/store.py:52: FutureWarning: This is an experimental API and will be changed in future.
  warnings.warn(
[INFO] 2024-08-16 07:39:44,252 api: [default] Rendezvous complete for workers. Result:
  restart_count=0
  master_addr=127.0.0.1
  master_port=29500
  group_rank=0
  group_world_size=1
  local_ranks=[0]
  role_ranks=[0]
  global_ranks=[0]
  role_world_sizes=[1]
  global_world_sizes=[1]

[INFO] 2024-08-16 07:39:44,252 api: [default] Starting worker group
[INFO] 2024-08-16 07:39:44,252 __init__: Setting worker0 reply file to: /tmp/torchelastic_73suzzko/none_td9et18n/attempt_0/0/error.json
[W ProcessGroupNCCL.cpp:1569] Rank 0 using best-guess GPU 0 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
main.py --backbone mit_b3 --dataset nyudv2 -c nyudv2_mit_b3
-----------------Model Params--------------------------------------
backbone: mit_b3
dpr: 0.4
--------------------------------------------------------------
Loaded Segmenter mit_b3, #PARAMS=74.55M
-------------------------Optimizer Params--------------------
weight_decay: 0.01
lrs: [6e-05, 3e-05, 1.5e-05]
----------------------------------------------------------------
Created train set 795 examples, val set 654 examples
Training Stage 0
  0%|                                                                                                                                                  | 0/397 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 678, in <module>
    main()
  File "main.py", line 641, in main
    train(
  File "main.py", line 383, in train
    for i, sample in tqdm(enumerate(train_loader), total=len(train_loader)):
  File "/anaconda3/envs/GeminiF/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/anaconda3/envs/GeminiF/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/anaconda3/envs/GeminiF/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/anaconda3/envs/GeminiF/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/anaconda3/envs/GeminiF/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/anaconda3/envs/GeminiF/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/anaconda3/envs/GeminiF/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/anaconda3/envs/GeminiF/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/GeminiFusion/utils/datasets.py", line 99, in __getitem__
    sample = self.transform_trn(sample)
  File "/anaconda3/envs/GeminiF/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 60, in __call__
    img = t(img)
  File "/GeminiFusion/utils/transforms.py", line 308, in __call__
    sample[key] = torch.from_numpy(sample[key].transpose((2, 0, 1))).to(
TypeError: can't convert np.ndarray of type numpy.uint16. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

[ERROR] 2024-08-16 07:40:09,290 api: failed (exitcode: 1) local_rank: 0 (pid: 939546) of binary: /anaconda3/envs/GeminiF/bin/python
[ERROR] 2024-08-16 07:40:09,290 local_elastic_agent: [default] Worker group failed
[INFO] 2024-08-16 07:40:09,290 api: [default] Worker group FAILED. 3/3 attempts left; will restart worker group
[INFO] 2024-08-16 07:40:09,290 api: [default] Stopping worker group
[INFO] 2024-08-16 07:40:09,290 api: [default] Rendezvous'ing worker group
[INFO] 2024-08-16 07:40:09,290 static_tcp_rendezvous: Creating TCPStore as the c10d::Store implementation
[INFO] 2024-08-16 07:40:09,290 api: [default] Rendezvous complete for workers. Result:
  restart_count=1
  master_addr=127.0.0.1
  master_port=29500
  group_rank=0
  group_world_size=1
  local_ranks=[0]
  role_ranks=[0]
  global_ranks=[0]
  role_world_sizes=[1]
  global_world_sizes=[1]

[INFO] 2024-08-16 07:40:09,290 api: [default] Starting worker group
[INFO] 2024-08-16 07:40:09,291 __init__: Setting worker0 reply file to: /tmp/torchelastic_73suzzko/none_td9et18n/attempt_1/0/error.json


Could you give me some advice on how to solve it?

**Comment by peter-wang321** [comment]
Update about the process:

I solved the issue about the errors:
TypeError: can't convert np.ndarray of type numpy.uint16. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

By transforming uint16 to float 16 in the class ToTensor(object):

And now I can run it in just one GPU. 3 GPUs still do not work well. I am not sure whether it needs additional setting for the distributed training.

**Comment by peter-wang321** [comment]
Thanks a lot. I am still working on this repo, hoping to reproduce the results immediately. Could you show the environment version for this repo.?
Python+Pytorch+CUDA. 

I noticed most of the errors are from the environments.

My setting is 
Python 3.8
Pytorch 3.9+cu111

The errors remain. I found that the single GPU could not handle it.

Thanks a lot.

**Comment by peter-wang321** [comment]
Thanks a lot. I am still working on this repo, hoping to reproduce the results immediately. Could you show the environment version for this repo.?
Python+Pytorch+CUDA.

I noticed most of the errors are from the environments.

My setting is
Python 3.8
Pytorch 1.9.0+cu111

The errors remain. I found that the single GPU could not handle it.

Thanks a lot.

**Comment by JiaDingCN** [comment]
Closed since the issue is solved here and [there](https://github.com/JiaDingCN/GeminiFusion/issues/8#issue-2471523363)
